// SPEC.md §10: C++ / Java / Python for each operation, mapped to the pseudocode lines in ./pseudocode.ts.
// Java follows algs4 (Graph/Digraph with adj(v), marked[], edgeTo[]; BreadthFirstPaths,
// DepthFirstSearch, CC, DepthFirstOrder, KosarajuSharirSCC).
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const addEdge: OperationSnippets = {
  java: code([
    ['public void addEdge(int v, int w) {', 1],
    ['    validateVertex(v); validateVertex(w);', 2],
    ['    adj[v].add(w);', 3],
    ['    if (!directed) adj[w].add(v);', 3],
    ['    E++;', 3],
    '}',
  ]),
  cpp: code([
    ['void addEdge(int v, int w) {', 1],
    ['    if (std::max(v, w) >= (int)adj.size()) adj.resize(std::max(v, w) + 1);', 2],
    ['    adj[v].push_back(w);', 3],
    ['    if (!directed) adj[w].push_back(v);', 3],
    ['    E++;', 3],
    '}',
  ]),
  python: code([
    ['def add_edge(self, v, w):', 1],
    ['    for u in (v, w):', 2],
    ['        self.adj.setdefault(u, [])', 2],
    ['    self.adj[v].append(w)', 3],
    ['    if not self.directed:', 3],
    ['        self.adj[w].append(v)', 3],
  ]),
}

const bfs: OperationSnippets = {
  java: code([
    ['private void bfs(Graph G, int s) {', 1],
    ['    Queue<Integer> queue = new Queue<>();', 2],
    ['    marked[s] = true;', 2],
    ['    queue.enqueue(s);', 2],
    ['    while (!queue.isEmpty()) {', 3],
    ['        int v = queue.dequeue();', 4],
    ['        for (int w : G.adj(v)) {', 5],
    ['            if (!marked[w]) {', 6],
    ['                edgeTo[w] = v;', 7],
    ['                marked[w] = true;', 7],
    ['                queue.enqueue(w);', 8],
    '            }',
    '        }',
    '    }',
    '}',
  ]),
  cpp: code([
    ['void bfs(const Graph& G, int s) {', 1],
    ['    std::queue<int> queue;', 2],
    ['    marked[s] = true;', 2],
    ['    queue.push(s);', 2],
    ['    while (!queue.empty()) {', 3],
    ['        int v = queue.front(); queue.pop();', 4],
    ['        for (int w : G.adj(v)) {', 5],
    ['            if (!marked[w]) {', 6],
    ['                edgeTo[w] = v;', 7],
    ['                marked[w] = true;', 7],
    ['                queue.push(w);', 8],
    '            }',
    '        }',
    '    }',
    '}',
  ]),
  python: code([
    ['def bfs(G, s):', 1],
    ['    marked = {s}', 2],
    ['    edge_to = {}', 2],
    ['    queue = deque([s])', 2],
    ['    while queue:', 3],
    ['        v = queue.popleft()', 4],
    ['        for w in G.adj[v]:', 5],
    ['            if w not in marked:', 6],
    ['                marked.add(w)', 7],
    ['                edge_to[w] = v', 7],
    ['                queue.append(w)', 8],
    ['    return edge_to', 3],
  ]),
}

const dfs: OperationSnippets = {
  java: code([
    ['private void dfs(Graph G, int v) {', 1],
    ['    marked[v] = true;', 2],
    ['    for (int w : G.adj(v)) {', 3],
    ['        if (!marked[w]) {', 4],
    ['            edgeTo[w] = v;', 5],
    ['            dfs(G, w);', 6],
    '        }',
    '    }',
    '}',
  ]),
  cpp: code([
    ['void dfs(const Graph& G, int v) {', 1],
    ['    marked[v] = true;', 2],
    ['    for (int w : G.adj(v)) {', 3],
    ['        if (!marked[w]) {', 4],
    ['            edgeTo[w] = v;', 5],
    ['            dfs(G, w);', 6],
    '        }',
    '    }',
    '}',
  ]),
  python: code([
    ['def dfs(G, v, marked, edge_to):', 1],
    ['    marked.add(v)', 2],
    ['    for w in G.adj[v]:', 3],
    ['        if w not in marked:', 4],
    ['            edge_to[w] = v', 5],
    ['            dfs(G, w, marked, edge_to)', 6],
  ]),
}

const cc: OperationSnippets = {
  java: code([
    ['public CC(Graph G) {', 1],
    ['    count = 0;', 2],
    ['    for (int v = 0; v < G.V(); v++) {', 3],
    ['        if (!marked[v]) {', 4],
    ['            dfs(G, v);', 6],
    ['            count++;', 5],
    '        }',
    '    }',
    '}',
    ['private void dfs(Graph G, int v) {', 6],
    ['    marked[v] = true;', 6],
    ['    id[v] = count;', 6],
    ['    for (int w : G.adj(v))', 6],
    ['        if (!marked[w]) dfs(G, w);', 6],
    '}',
  ]),
  cpp: code([
    ['int connectedComponents(const Graph& G) {', 1],
    ['    int count = 0;', 2],
    ['    for (int v = 0; v < G.V(); v++) {', 3],
    ['        if (!marked[v]) {', 4],
    ['            count++;', 5],
    ['            dfs(G, v, count);', 6],
    '        }',
    '    }',
    '    return count;',
    '}',
    ['void dfs(const Graph& G, int v, int component) {', 6],
    ['    marked[v] = true;', 6],
    ['    id[v] = component;', 6],
    ['    for (int w : G.adj(v))', 6],
    ['        if (!marked[w]) dfs(G, w, component);', 6],
    '}',
  ]),
  python: code([
    ['def connected_components(G):', 1],
    ['    count = 0', 2],
    ['    component = {}', 2],
    ['    for v in G.vertices():', 3],
    ['        if v not in component:', 4],
    ['            count += 1', 5],
    ['            dfs(G, v, count, component)', 6],
    '    return count, component',
    '',
    ['def dfs(G, v, c, component):', 6],
    ['    component[v] = c', 6],
    ['    for w in G.adj[v]:', 6],
    ['        if w not in component:', 6],
    ['            dfs(G, w, c, component)', 6],
  ]),
}

const topo: OperationSnippets = {
  java: code([
    ['public Iterable<Integer> topologicalOrder(Digraph G) {', 1],
    ['    for (int v = 0; v < G.V(); v++)', 2],
    ['        if (!marked[v]) dfs(G, v);', 3],
    ['    return reversePost;   // a Stack: last finished comes out first', 5],
    '}',
    ['private void dfs(Digraph G, int v) {', 4],
    ['    marked[v] = true;', 4],
    ['    for (int w : G.adj(v))', 4],
    ['        if (!marked[w]) dfs(G, w);', 4],
    ['    reversePost.push(v);', 4],
    '}',
  ]),
  cpp: code([
    ['std::vector<int> topologicalOrder(const Digraph& G) {', 1],
    ['    for (int v = 0; v < G.V(); v++)', 2],
    ['        if (!marked[v]) dfs(G, v);', 3],
    ['    std::reverse(postorder.begin(), postorder.end());', 5],
    ['    return postorder;', 5],
    '}',
    ['void dfs(const Digraph& G, int v) {', 4],
    ['    marked[v] = true;', 4],
    ['    for (int w : G.adj(v))', 4],
    ['        if (!marked[w]) dfs(G, w);', 4],
    ['    postorder.push_back(v);', 4],
    '}',
  ]),
  python: code([
    ['def topological_order(G):', 1],
    ['    marked, postorder = set(), []', 2],
    ['    for v in G.vertices():', 2],
    ['        if v not in marked:', 3],
    ['            dfs_postorder(G, v, marked, postorder)', 4],
    ['    return list(reversed(postorder))', 5],
    '',
    ['def dfs_postorder(G, v, marked, postorder):', 4],
    ['    marked.add(v)', 4],
    ['    for w in G.adj[v]:', 4],
    ['        if w not in marked:', 4],
    ['            dfs_postorder(G, w, marked, postorder)', 4],
    ['    postorder.append(v)', 4],
  ]),
}

const scc: OperationSnippets = {
  java: code([
    ['public KosarajuSharirSCC(Digraph G) {', 1],
    ['    DepthFirstOrder dfs = new DepthFirstOrder(G.reverse());', 2],
    ['    for (int v : dfs.reversePost()) {', 3],
    ['        if (!marked[v]) {', 4],
    ['            dfs(G, v);', 5],
    ['            count++;', 5],
    '        }',
    '    }',
    '}',
    ['private void dfs(Digraph G, int v) {', 5],
    ['    marked[v] = true;', 5],
    ['    id[v] = count;', 5],
    ['    for (int w : G.adj(v))', 5],
    ['        if (!marked[w]) dfs(G, w);', 5],
    '}',
  ]),
  cpp: code([
    ['int strongComponents(const Digraph& G) {', 1],
    ['    std::vector<int> order = reversePostorder(G.reverse());', 2],
    ['    int count = 0;', 2],
    ['    for (int v : order) {', 3],
    ['        if (!marked[v]) {', 4],
    ['            count++;', 5],
    ['            dfs(G, v, count);', 5],
    '        }',
    '    }',
    '    return count;',
    '}',
    ['void dfs(const Digraph& G, int v, int component) {', 5],
    ['    marked[v] = true;', 5],
    ['    id[v] = component;', 5],
    ['    for (int w : G.adj(v))', 5],
    ['        if (!marked[w]) dfs(G, w, component);', 5],
    '}',
  ]),
  python: code([
    ['def strong_components(G):', 1],
    ['    order = reverse_postorder(G.reverse())', 2],
    ['    count, component = 0, {}', 2],
    ['    for v in order:', 3],
    ['        if v not in component:', 4],
    ['            count += 1', 5],
    ['            dfs(G, v, count, component)', 5],
    '    return count, component',
    '',
    ['def dfs(G, v, c, component):', 5],
    ['    component[v] = c', 5],
    ['    for w in G.adj[v]:', 5],
    ['        if w not in component:', 5],
    ['            dfs(G, w, c, component)', 5],
  ]),
}

export const graphSnippets: Record<string, OperationSnippets> = {
  'add-edge': addEdge,
  bfs,
  dfs,
  'connected-components': cc,
  'topological-sort': topo,
  'strong-components': scc,
}
