// SPEC.md §19.0 quiz. Explanations cite the week reference; predict questions run on the seed.
import type { QuizQuestion } from '@/types/case-study'

export const studyPlanQuiz: QuizQuestion[] = [
  {
    kind: 'choice',
    id: 'plan-hash-not-bst',
    prompt: 'Why does the planner find vertex numbers with a hash table rather than a binary search tree?',
    choices: [
      'A hash table keeps the codes sorted, which the plan needs.',
      'The planner only looks up exact codes, so it has no use for the order a BST keeps.',
      'A binary search tree cannot store text keys.',
      'A hash table never has collisions.',
    ],
    answer: 1,
    explanation: 'Week 12: a hash table trades the ordering a BST preserves for near-constant lookups of exact keys. The planner never asks for the next code or a range of codes.',
    topicSlug: 'hash-table',
  },
  {
    kind: 'choice',
    id: 'plan-property-l',
    prompt: 'The index has M = 11 buckets and N = 8 courses. What does Property L say a lookup costs?',
    choices: ['About lg N compares', 'About N compares', 'About N/M compares, which is less than 1 here', 'Exactly one probe, whatever N is'],
    answer: 2,
    explanation: 'Week 12, Property L: in a separate-chaining table with M lists and N keys, search and insert take a number of compares proportional to N/M. Here 8/11 is about 0.73.',
    topicSlug: 'hash-table',
  },
  {
    kind: 'choice',
    id: 'plan-directed',
    prompt: 'Why must the prerequisite graph be directed?',
    choices: [
      'Depth-first search only runs on directed graphs.',
      'Directed graphs take less memory.',
      'An undirected graph can hold at most 10 vertices.',
      'PR1 before PR2 does not mean PR2 before PR1.',
    ],
    answer: 3,
    explanation: 'Weeks 13–15: a prerequisite is one-way, so the problem needs a directed graph. Treating a one-way relation as symmetric silently breaks the algorithms built on top of it.',
    topicSlug: 'graph',
  },
  {
    kind: 'choice',
    id: 'plan-dag',
    prompt: 'When does a set of prerequisites have a valid study plan?',
    choices: [
      'Exactly when the prerequisite digraph has no directed cycle',
      'When every course has at most one prerequisite',
      'When the digraph is connected',
      'Always, once the codes are sorted',
    ],
    answer: 0,
    explanation: 'Weeks 13–15: a digraph has a topological order if and only if it is a DAG, a directed graph with no directed cycle.',
    topicSlug: 'graph',
  },
  {
    kind: 'choice',
    id: 'plan-reverse-postorder',
    prompt: 'Which order does the planner print?',
    choices: ['The order DFS first visits each course', 'The reverse of the DFS postorder', 'The BFS order from course 0', 'The codes sorted from A to Z'],
    answer: 1,
    explanation: 'Weeks 13–15: reverse postorder of a DAG is a topological sort. A course joins the postorder only after every course that needs it has joined.',
    topicSlug: 'graph',
  },
  {
    kind: 'choice',
    id: 'plan-v-plus-e',
    prompt: 'How much time does DFS need to topologically sort the prerequisite digraph?',
    choices: ['Time proportional to V²', 'Time proportional to E log V', 'Time proportional to V × E', 'Time proportional to V + E'],
    answer: 3,
    explanation: 'Weeks 13–15: DFS can topologically sort a DAG in time proportional to V + E.',
    topicSlug: 'graph',
  },
  {
    kind: 'predict',
    id: 'plan-predict-alphabetical',
    prompt: 'The alphabetical plan is AI, DB, DSA, DSC, MTH, PR1, PR2, WEB. The next edge to check is PR2 to DSA. What does the planner find?',
    operationId: 'plan-alphabetical',
    variant: 'alphabetical',
    input: undefined,
    stepIndex: 1,
    expect: 'DSA comes before its prerequisite PR2',
    choices: [
      'PR2 comes before DSA, so this prerequisite holds.',
      'DSA comes before its prerequisite PR2, so it counts a violation.',
      'The planner stops because it found a cycle.',
      'The planner skips the edge because DSA has two prerequisites.',
    ],
    answer: 1,
    explanation: 'DSA sits third in the sorted list and PR2 seventh, so this plan takes DSA before its prerequisite. Letter order carries no information about prerequisites.',
    topicSlug: 'graph',
  },
  {
    kind: 'predict',
    id: 'plan-predict-marked',
    prompt: 'The search is visiting DSA and looks at AI, which it already visited and finished from MTH. What happens next?',
    operationId: 'plan-topological',
    variant: 'topological',
    input: undefined,
    stepIndex: 15,
    expect: 'AI is already marked, so skip it',
    choices: [
      'AI is still on the call stack, so report a cycle.',
      'Visit AI a second time.',
      'AI is already marked, so skip it.',
      'Remove AI from the postorder.',
    ],
    answer: 2,
    explanation: 'AI finished earlier and left the call stack, so the edge from DSA to AI does not close a cycle. Only an edge to a course that is still on the call stack does (Weeks 13–15).',
    topicSlug: 'graph',
  },
]
