// SPEC.md §10: C++ / Java / Python for each operation, mapped to the pseudocode lines in ./pseudocode.ts.
// Java follows the algs4 shape: a linked Node per bucket for chaining, a keys[] array for probing.
// hash(key) is key mod M throughout; M is 11 in the visualizer.
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const chaining: OperationSnippets = {
  java: code([
    ['public void insert(int key) {', 1],
    ['    int i = hash(key);', 2],
    ['    for (Node x = bucket[i]; x != null; x = x.next)', 3],
    ['        if (x.key == key) return;', 3],
    ['    bucket[i] = new Node(key, bucket[i]);', 3],
    '}',
    ['public boolean search(int key) {', 4],
    ['    int i = hash(key);', 5],
    ['    for (Node x = bucket[i]; x != null; x = x.next)', 6],
    ['        if (x.key == key) return true;', 6],
    ['    return false;', 6],
    '}',
    ['public void delete(int key) {', 7],
    ['    int i = hash(key);', 8],
    ['    bucket[i] = delete(bucket[i], key);', 9],
    '}',
    ['private Node delete(Node x, int key) {', 9],
    ['    if (x == null) return null;', 9],
    ['    if (x.key == key) return x.next;', 9],
    ['    x.next = delete(x.next, key);', 9],
    ['    return x;', 9],
    '}',
  ]),
  cpp: code([
    ['void insert(int key) {', 1],
    ['    int i = hash(key);', 2],
    ['    for (int k : bucket[i])', 3],
    ['        if (k == key) return;', 3],
    ['    bucket[i].push_back(key);', 3],
    '}',
    ['bool search(int key) {', 4],
    ['    int i = hash(key);', 5],
    ['    for (int k : bucket[i])', 6],
    ['        if (k == key) return true;', 6],
    ['    return false;', 6],
    '}',
    ['void remove(int key) {', 7],
    ['    int i = hash(key);', 8],
    ['    bucket[i].remove(key);   // std::list<int>', 9],
    '}',
  ]),
  python: code([
    ['def insert(self, key):', 1],
    ['    i = self.hash(key)', 2],
    ['    if key not in self.bucket[i]:', 3],
    ['        self.bucket[i].append(key)', 3],
    '',
    ['def search(self, key):', 4],
    ['    i = self.hash(key)', 5],
    ['    return key in self.bucket[i]', 6],
    '',
    ['def delete(self, key):', 7],
    ['    i = self.hash(key)', 8],
    ['    if key in self.bucket[i]:', 9],
    ['        self.bucket[i].remove(key)', 9],
  ]),
}

const probing: OperationSnippets = {
  java: code([
    ['public void insert(int key) {', 1],
    ['    int i = hash(key);', 2],
    ['    while (keys[i] != EMPTY && keys[i] != key)', 3],
    ['        i = (i + 1) % M;', 4],
    ['    keys[i] = key;', 5],
    '}',
    ['public boolean search(int key) {', 6],
    ['    int i = hash(key);', 7],
    ['    while (keys[i] != EMPTY) {', 8],
    ['        if (keys[i] == key) return true;', 9],
    ['        i = (i + 1) % M;', 10],
    '    }',
    ['    return false;', 11],
    '}',
    ['public void delete(int key) {', 12],
    ['    int i = hash(key);', 13],
    ['    while (keys[i] != EMPTY && keys[i] != key) i = (i + 1) % M;', 13],
    ['    if (keys[i] == EMPTY) return;', 14],
    ['    keys[i] = EMPTY;', 15],
    ['    i = (i + 1) % M;', 16],
    ['    while (keys[i] != EMPTY) {', 16],
    ['        int k = keys[i];', 16],
    ['        keys[i] = EMPTY;', 16],
    ['        insert(k);', 16],
    ['        i = (i + 1) % M;', 16],
    '    }',
    '}',
  ]),
  cpp: code([
    ['void insert(int key) {', 1],
    ['    int i = hash(key);', 2],
    ['    while (keys[i] != EMPTY && keys[i] != key)', 3],
    ['        i = (i + 1) % M;', 4],
    ['    keys[i] = key;', 5],
    '}',
    ['bool search(int key) {', 6],
    ['    int i = hash(key);', 7],
    ['    while (keys[i] != EMPTY) {', 8],
    ['        if (keys[i] == key) return true;', 9],
    ['        i = (i + 1) % M;', 10],
    '    }',
    ['    return false;', 11],
    '}',
    ['void remove(int key) {', 12],
    ['    int i = hash(key);', 13],
    ['    while (keys[i] != EMPTY && keys[i] != key) i = (i + 1) % M;', 13],
    ['    if (keys[i] == EMPTY) return;', 14],
    ['    keys[i] = EMPTY;', 15],
    ['    i = (i + 1) % M;', 16],
    ['    while (keys[i] != EMPTY) {', 16],
    ['        int k = keys[i];', 16],
    ['        keys[i] = EMPTY;', 16],
    ['        insert(k);', 16],
    ['        i = (i + 1) % M;', 16],
    '    }',
    '}',
  ]),
  python: code([
    ['def insert(self, key):', 1],
    ['    i = self.hash(key)', 2],
    ['    while self.keys[i] is not None and self.keys[i] != key:', 3],
    ['        i = (i + 1) % self.M', 4],
    ['    self.keys[i] = key', 5],
    '',
    ['def search(self, key):', 6],
    ['    i = self.hash(key)', 7],
    ['    while self.keys[i] is not None:', 8],
    ['        if self.keys[i] == key:', 9],
    ['            return True', 9],
    ['        i = (i + 1) % self.M', 10],
    ['    return False', 11],
    '',
    ['def delete(self, key):', 12],
    ['    i = self.hash(key)', 13],
    ['    while self.keys[i] is not None and self.keys[i] != key:', 13],
    ['        i = (i + 1) % self.M', 13],
    ['    if self.keys[i] is None:', 14],
    ['        return', 14],
    ['    self.keys[i] = None', 15],
    ['    i = (i + 1) % self.M', 16],
    ['    while self.keys[i] is not None:', 16],
    ['        k = self.keys[i]', 16],
    ['        self.keys[i] = None', 16],
    ['        self.insert(k)', 16],
    ['        i = (i + 1) % self.M', 16],
  ]),
}

export const hashTableSnippets: Record<string, OperationSnippets> = {
  'chain-insert': chaining,
  'chain-search': chaining,
  'chain-delete': chaining,
  'probe-insert': probing,
  'probe-search': probing,
  'probe-delete': probing,
}
