// SPEC.md §10.8: C++ / Java / Python for each operation, mapped to the pseudocode lines in ./pseudocode.ts.
// Java follows algs4 ResizingArrayStack, Stack, and Evaluate; C++ and Python are direct translations.
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const array: OperationSnippets = {
  java: code([
    ['public void push(Item item) {', 1],
    ['    if (n == a.length) resize(2 * a.length);', 2],
    ['    a[n++] = item;', 3],
    '}',
    ['public Item pop() {', 4],
    ['    Item item = a[n - 1];', 5],
    ['    a[n - 1] = null;', 5],
    ['    n--;', 5],
    ['    if (n > 0 && n == a.length / 4) resize(a.length / 2);', 6],
    ['    return item;', 7],
    '}',
    ['private void resize(int capacity) {', 8],
    ['    Item[] copy = (Item[]) new Object[capacity];', 9],
    ['    for (int i = 0; i < n; i++)', 10],
    ['        copy[i] = a[i];', 10],
    ['    a = copy;', 11],
    '}',
  ]),
  cpp: code([
    ['void push(int item) {', 1],
    ['    if (n == capacity) resize(2 * capacity);', 2],
    ['    a[n++] = item;', 3],
    '}',
    ['int pop() {', 4],
    ['    int item = a[--n];', 5],
    ['    if (n > 0 && n == capacity / 4) resize(capacity / 2);', 6],
    ['    return item;', 7],
    '}',
    ['void resize(int newCapacity) {', 8],
    ['    int* copy = new int[newCapacity];', 9],
    ['    for (int i = 0; i < n; i++)', 10],
    ['        copy[i] = a[i];', 10],
    ['    delete[] a;', 11],
    ['    a = copy; capacity = newCapacity;', 11],
    '}',
  ]),
  python: code([
    ['def push(self, item):', 1],
    ['    if self.n == len(self.a):', 2],
    ['        self.resize(2 * len(self.a))', 2],
    ['    self.a[self.n] = item', 3],
    ['    self.n += 1', 3],
    '',
    ['def pop(self):', 4],
    ['    self.n -= 1', 5],
    ['    item = self.a[self.n]', 5],
    ['    self.a[self.n] = None', 5],
    ['    if self.n > 0 and self.n == len(self.a) // 4:', 6],
    ['        self.resize(len(self.a) // 2)', 6],
    ['    return item', 7],
    '',
    ['def resize(self, capacity):', 8],
    ['    copy = [None] * capacity', 9],
    ['    for i in range(self.n):', 10],
    ['        copy[i] = self.a[i]', 10],
    ['    self.a = copy', 11],
  ]),
}

const linked: OperationSnippets = {
  java: code([
    ['public void push(Item item) {', 1],
    ['    Node oldfirst = first;', 2],
    ['    first = new Node();', 3],
    ['    first.item = item;', 3],
    ['    first.next = oldfirst;', 4],
    ['    n++;', 5],
    '}',
    ['public Item pop() {', 6],
    ['    Item item = first.item;', 7],
    ['    first = first.next;', 8],
    ['    n--;', 9],
    ['    return item;', 10],
    '}',
  ]),
  cpp: code([
    ['void push(int item) {', 1],
    ['    Node* oldfirst = first;', 2],
    ['    first = new Node{item, nullptr};', 3],
    ['    first->next = oldfirst;', 4],
    ['    n++;', 5],
    '}',
    ['int pop() {', 6],
    ['    int item = first->item;', 7],
    ['    Node* old = first;', 7],
    ['    first = first->next;', 8],
    ['    delete old;', 8],
    ['    n--;', 9],
    ['    return item;', 10],
    '}',
  ]),
  python: code([
    ['def push(self, item):', 1],
    ['    oldfirst = self.first', 2],
    ['    self.first = Node(item, None)', 3],
    ['    self.first.next = oldfirst', 4],
    ['    self.n += 1', 5],
    '',
    ['def pop(self):', 6],
    ['    item = self.first.item', 7],
    ['    self.first = self.first.next', 8],
    ['    self.n -= 1', 9],
    ['    return item', 10],
  ]),
}

const evaluate: OperationSnippets = {
  java: code([
    ['public static double evaluate(String[] tokens) {', 1],
    ['    Stack<String> ops  = new Stack<String>();', 1],
    ['    Stack<Double> vals = new Stack<Double>();', 1],
    ['    for (String s : tokens) {', 2],
    ['        if      (s.equals("(")) ;', 3],
    ['        else if (s.equals("+") || s.equals("-")', 4],
    ['              || s.equals("*") || s.equals("/")) ops.push(s);', 4],
    ['        else if (s.equals(")")) {', 5],
    ['            String op = ops.pop();', 6],
    ['            double b = vals.pop();', 6],
    ['            double a = vals.pop();', 6],
    ['            if      (op.equals("+")) vals.push(a + b);', 7],
    ['            else if (op.equals("-")) vals.push(a - b);', 7],
    ['            else if (op.equals("*")) vals.push(a * b);', 7],
    ['            else if (op.equals("/")) vals.push(a / b);', 7],
    '        }',
    ['        else vals.push(Double.parseDouble(s));', 8],
    '    }',
    ['    return vals.pop();', 9],
    '}',
  ]),
  cpp: code([
    ['double evaluate(const std::vector<std::string>& tokens) {', 1],
    ['    std::stack<std::string> ops;', 1],
    ['    std::stack<double> vals;', 1],
    ['    for (const std::string& s : tokens) {', 2],
    ['        if (s == "(") continue;', 3],
    ['        else if (s == "+" || s == "-" || s == "*" || s == "/") ops.push(s);', 4],
    ['        else if (s == ")") {', 5],
    ['            std::string op = ops.top(); ops.pop();', 6],
    ['            double b = vals.top(); vals.pop();', 6],
    ['            double a = vals.top(); vals.pop();', 6],
    ['            if      (op == "+") vals.push(a + b);', 7],
    ['            else if (op == "-") vals.push(a - b);', 7],
    ['            else if (op == "*") vals.push(a * b);', 7],
    ['            else if (op == "/") vals.push(a / b);', 7],
    '        }',
    ['        else vals.push(std::stod(s));', 8],
    '    }',
    ['    double result = vals.top(); vals.pop();', 9],
    ['    return result;', 9],
    '}',
  ]),
  python: code([
    ['def evaluate(tokens):', 1],
    ['    ops, vals = [], []', 1],
    ['    for s in tokens:', 2],
    ['        if s == "(":', 3],
    ['            continue', 3],
    ['        elif s in ("+", "-", "*", "/"):', 4],
    ['            ops.append(s)', 4],
    ['        elif s == ")":', 5],
    ['            op = ops.pop()', 6],
    ['            b = vals.pop()', 6],
    ['            a = vals.pop()', 6],
    ['            if op == "+": vals.append(a + b)', 7],
    ['            elif op == "-": vals.append(a - b)', 7],
    ['            elif op == "*": vals.append(a * b)', 7],
    ['            elif op == "/": vals.append(a / b)', 7],
    ['        else:', 8],
    ['            vals.append(float(s))', 8],
    ['    return vals.pop()', 9],
  ]),
}

export const stackSnippets: Record<string, OperationSnippets> = {
  'array-push': array,
  'array-pop': array,
  'linked-push': linked,
  'linked-pop': linked,
  evaluate,
}
