// SPEC.md §19.0 quiz. Explanations cite the week reference; predict questions run on the seed.
import type { QuizQuestion } from '@/types/case-study'

export const triageQuiz: QuizQuestion[] = [
  {
    kind: 'choice',
    id: 'triage-fifo',
    prompt: 'Why does a plain FIFO queue fail the triage desk?',
    choices: [
      'Dequeue takes linear time.',
      'It cannot hold more than 15 patients.',
      'It treats patients in arrival order, so a critical patient waits behind milder cases.',
      'It loses patients when its array resizes.',
    ],
    answer: 2,
    explanation: 'Week 11: arrival order suffices only while every item has the same priority. Once priorities differ, the problem needs a priority queue. The bypassed counter in the Arrival queue design shows the cost.',
    topicSlug: 'binary-heap',
  },
  {
    kind: 'choice',
    id: 'triage-insert-cost',
    prompt: 'N patients are waiting in the heap. At most how many compares does admitting one more take?',
    choices: ['N', '1 + lg N', '2 lg N', 'N lg N'],
    answer: 1,
    explanation: 'Week 11: heap insert needs no more than 1 + lg N compares, and removing the maximum no more than 2 lg N.',
    topicSlug: 'binary-heap',
  },
  {
    kind: 'choice',
    id: 'triage-ordered-array',
    prompt: 'Why not keep the waiting list as an array sorted by urgency?',
    choices: [
      'Treating is fast, but an admission can take linear time to keep the array in order.',
      'A sorted array cannot store severities.',
      'Treating would need a full scan of the array.',
      'A sorted array cannot hold two patients with the same severity.',
    ],
    answer: 0,
    explanation: 'Week 11: every elementary implementation makes either insert or remove the maximum linear in the worst case. An ordered array makes removal fast and insertion slow.',
    topicSlug: 'binary-heap',
  },
  {
    kind: 'choice',
    id: 'triage-tie',
    prompt: 'Two waiting patients both have severity 4. Which one does the desk treat first?',
    choices: ['The one with the lower record number', 'Either one, chosen at random', 'The one admitted most recently', 'The one who arrived earlier'],
    answer: 3,
    explanation: 'The desk compares severity, then arrival, the way Week 11\'s stock exchange example ranks orders by price and then by time.',
    topicSlug: 'binary-heap',
  },
  {
    kind: 'choice',
    id: 'triage-root',
    prompt: 'Where does a max heap keep the most urgent patient?',
    choices: ['At the root, pq[1]', 'At the last position, pq[n]', 'In the leftmost leaf', 'Anywhere, so the heap must be scanned'],
    answer: 0,
    explanation: 'Week 11: in a heap-ordered tree each key is at least as large as the keys in its children, so the largest key is always at the root.',
    topicSlug: 'binary-heap',
  },
  {
    kind: 'choice',
    id: 'triage-btree',
    prompt: 'Why does the record archive use a B-tree instead of a binary search tree?',
    choices: [
      'A binary search tree cannot store integer keys.',
      'A B-tree keeps records in arrival order.',
      'Each node read is a block read, and a B-tree\'s high branching factor keeps every root-to-leaf path short.',
      'A binary search tree needs a hash function.',
    ],
    answer: 2,
    explanation: 'Week 10: get makes at most log_M(N) probes, and in a disk-backed tree each probe is a disk read. A BST branches two ways, and Week 9 shows it can grow as tall as a list on sorted input.',
    topicSlug: 'b-tree',
  },
  {
    kind: 'predict',
    id: 'triage-predict-tie',
    prompt: 'Patient #106 (severity 5) has swum up once and is now compared with #104, also severity 5. What happens next?',
    operationId: 'admit-priority',
    variant: 'priority',
    input: [5, 50],
    stepIndex: 9,
    expect: 'Heap order holds: #104 stays above #106',
    choices: [
      '#106 swims up and becomes the root.',
      'Heap order holds: #104 stays above #106.',
      '#104 sinks below #106.',
      'The desk treats #106 at once.',
    ],
    answer: 1,
    explanation: 'The severities tie, so the earlier arrival counts as more urgent. #104 arrived before #106, so #106 stops below it.',
    topicSlug: 'binary-heap',
  },
  {
    kind: 'predict',
    id: 'triage-predict-bypass',
    prompt: 'The arrival queue has just treated #101 (severity 2). What does the desk record next?',
    operationId: 'treat-arrival',
    variant: 'arrival',
    input: undefined,
    stepIndex: 1,
    expect: 'bypassed is now 1',
    choices: [
      'Nobody still waiting is more urgent than #101.',
      '#102 (severity 4) moves to the front because it is more urgent.',
      '#104 swims up to the front of the queue.',
      '#104 (severity 5) is more urgent and still waiting: bypassed is now 1.',
    ],
    answer: 3,
    explanation: '#104 is critical but arrived fourth, and a queue never reorders. A priority queue would have treated #104 first (Week 11).',
    topicSlug: 'queue',
  },
]
