// SPEC.md §19.2: C++ / Java / Python for each operation, mapped to the pseudocode lines in ./pseudocode.ts.
// Java follows algs4: MaxPQ<Patient> with swim and sink, Queue<Patient>, and BTree<Integer, Record> for the archive.
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const admitPriority: OperationSnippets = {
  java: code([
    ['public void admit(int severity, int record) {', 1],
    ['    if (archive.get(record) == null) archive.put(record, new Record(record));', 2],
    ['    Patient p = new Patient(nextArrival++, severity, record);', 3],
    ['    pq[++n] = p;', 4],
    ['    swim(n);', 4],
    '}',
    ['private void swim(int k) {', 5],
    ['    while (k > 1 && moreUrgent(k, k / 2)) {', 6],
    ['        exch(k, k / 2);', 7],
    ['        k = k / 2;', 7],
    '    }',
    '}',
  ]),
  cpp: code([
    ['void admit(int severity, int record) {', 1],
    ['    if (!archive.contains(record)) archive.put(record);', 2],
    ['    Patient p{nextArrival++, severity, record};', 3],
    ['    pq.push_back(p);   // pq[0] is unused', 4],
    ['    swim(pq.size() - 1);', 4],
    '}',
    ['void swim(int k) {', 5],
    ['    while (k > 1 && moreUrgent(pq[k], pq[k / 2])) {', 6],
    ['        std::swap(pq[k], pq[k / 2]);', 7],
    ['        k /= 2;', 7],
    '    }',
    '}',
  ]),
  python: code([
    ['def admit(self, severity, record):', 1],
    ['    if self.archive.get(record) is None: self.archive.put(record)', 2],
    ['    p = Patient(self.next_arrival, severity, record)', 3],
    ['    self.next_arrival += 1', 3],
    ['    self.pq.append(p)   # pq[0] is unused', 4],
    ['    self.swim(len(self.pq) - 1)', 4],
    '',
    ['def swim(self, k):', 5],
    ['    while k > 1 and more_urgent(self.pq[k], self.pq[k // 2]):', 6],
    ['        self.pq[k], self.pq[k // 2] = self.pq[k // 2], self.pq[k]', 7],
    ['        k //= 2', 7],
  ]),
}

const admitArrival: OperationSnippets = {
  java: code([
    ['public void admit(int severity, int record) {', 1],
    ['    if (archive.get(record) == null) archive.put(record, new Record(record));', 2],
    ['    Patient p = new Patient(nextArrival++, severity, record);', 3],
    ['    queue.enqueue(p);', 4],
    '}',
  ]),
  cpp: code([
    ['void admit(int severity, int record) {', 1],
    ['    if (!archive.contains(record)) archive.put(record);', 2],
    ['    Patient p{nextArrival++, severity, record};', 3],
    ['    queue.push(p);', 4],
    '}',
  ]),
  python: code([
    ['def admit(self, severity, record):', 1],
    ['    if self.archive.get(record) is None: self.archive.put(record)', 2],
    ['    p = Patient(self.next_arrival, severity, record)', 3],
    ['    self.next_arrival += 1', 3],
    ['    self.queue.append(p)   # a collections.deque', 4],
  ]),
}

const treatPriority: OperationSnippets = {
  java: code([
    ['public Patient treatNext() {', 1],
    ['    if (n == 0) return null;', 2],
    ['    Patient p = pq[1];', 3],
    ['    exch(1, n--);', 3],
    ['    pq[n + 1] = null;', 3],
    ['    sink(1);', 4],
    '    return p;',
    '}',
    ['private void sink(int k) {', 5],
    ['    while (2 * k <= n) {', 6],
    ['        int j = 2 * k;', 7],
    ['        if (j < n && moreUrgent(j + 1, j)) j++;', 7],
    ['        if (!moreUrgent(j, k)) break;', 8],
    ['        exch(k, j);', 9],
    ['        k = j;', 9],
    '    }',
    '}',
  ]),
  cpp: code([
    ['std::optional<Patient> treatNext() {', 1],
    ['    if (n == 0) return std::nullopt;', 2],
    ['    Patient p = pq[1];', 3],
    ['    pq[1] = pq[n--];', 3],
    ['    sink(1);', 4],
    '    return p;',
    '}',
    ['void sink(int k) {', 5],
    ['    while (2 * k <= n) {', 6],
    ['        int j = 2 * k;', 7],
    ['        if (j < n && moreUrgent(pq[j + 1], pq[j])) j++;', 7],
    ['        if (!moreUrgent(pq[j], pq[k])) break;', 8],
    ['        std::swap(pq[k], pq[j]);', 9],
    ['        k = j;', 9],
    '    }',
    '}',
  ]),
  python: code([
    ['def treat_next(self):', 1],
    ['    if self.n == 0: return None', 2],
    ['    p = self.pq[1]', 3],
    ['    self.pq[1] = self.pq[self.n]; self.n -= 1', 3],
    ['    self.sink(1)', 4],
    '    return p',
    '',
    ['def sink(self, k):', 5],
    ['    while 2 * k <= self.n:', 6],
    ['        j = 2 * k', 7],
    ['        if j < self.n and more_urgent(self.pq[j + 1], self.pq[j]): j += 1', 7],
    ['        if not more_urgent(self.pq[j], self.pq[k]): break', 8],
    ['        self.pq[k], self.pq[j] = self.pq[j], self.pq[k]', 9],
    ['        k = j', 9],
  ]),
}

const treatArrival: OperationSnippets = {
  java: code([
    ['public Patient treatNext() {', 1],
    ['    if (queue.isEmpty()) return null;', 2],
    ['    Patient p = queue.dequeue();', 3],
    ['    for (Patient w : queue)', 4],
    ['        if (moreUrgent(w, p)) { bypassed++; break; }', 4],
    '    return p;',
    '}',
  ]),
  cpp: code([
    ['std::optional<Patient> treatNext() {', 1],
    ['    if (queue.empty()) return std::nullopt;', 2],
    ['    Patient p = queue.front(); queue.pop_front();', 3],
    ['    for (const Patient& w : queue)', 4],
    ['        if (moreUrgent(w, p)) { bypassed++; break; }', 4],
    '    return p;',
    '}',
  ]),
  python: code([
    ['def treat_next(self):', 1],
    ['    if not self.queue: return None', 2],
    ['    p = self.queue.popleft()', 3],
    ['    if any(more_urgent(w, p) for w in self.queue):', 4],
    ['        self.bypassed += 1', 4],
    '    return p',
  ]),
}

const findRecord: OperationSnippets = {
  java: code([
    ['public Record findRecord(int record) {', 1],
    ['    Node x = root;', 2],
    ['    for (int ht = height; ht > 0; ht--) {', 3],
    ['        int j = 0;', 4],
    ['        while (j + 1 < x.m && record >= x.children[j + 1].key) j++;', 4],
    ['        x = x.children[j].next;', 4],
    '    }',
    ['    for (int j = 0; j < x.m; j++)', 5],
    ['        if (x.children[j].key == record) return x.children[j].val;', 5],
    ['    return null;', 5],
    '}',
  ]),
  cpp: code([
    ['const Record* findRecord(int record) {', 1],
    ['    Node* x = root;', 2],
    ['    for (int ht = height; ht > 0; ht--) {', 3],
    ['        int j = 0;', 4],
    ['        while (j + 1 < x->m && record >= x->entries[j + 1].key) j++;', 4],
    ['        x = x->entries[j].next;', 4],
    '    }',
    ['    for (int j = 0; j < x->m; j++)', 5],
    ['        if (x->entries[j].key == record) return &x->entries[j].val;', 5],
    ['    return nullptr;', 5],
    '}',
  ]),
  python: code([
    ['def find_record(self, record):', 1],
    ['    x = self.root', 2],
    ['    for _ in range(self.height):', 3],
    ['        j = 0', 4],
    ['        while j + 1 < len(x.entries) and record >= x.entries[j + 1].key: j += 1', 4],
    ['        x = x.entries[j].next', 4],
    ['    for e in x.entries:', 5],
    ['        if e.key == record: return e.val', 5],
    ['    return None', 5],
  ]),
}

export const triageSnippets: Record<string, OperationSnippets> = {
  'admit-priority': admitPriority,
  'admit-arrival': admitArrival,
  'treat-priority': treatPriority,
  'treat-arrival': treatArrival,
  'find-record': findRecord,
}
