// SPEC.md §10.7: C++ / Java / Python for each operation, mapped to the pseudocode lines in ./pseudocode.ts.
// Java follows algs4 ResizingArrayQueue and Queue; C++ and Python are direct translations.
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const array: OperationSnippets = {
  java: code([
    ['public void enqueue(Item item) {', 1],
    ['    if (n == q.length) resize(2 * q.length);', 2],
    ['    q[last++] = item;', 3],
    ['    if (last == q.length) last = 0;', 4],
    ['    n++;', 5],
    '}',
    ['public Item dequeue() {', 6],
    ['    Item item = q[first];', 7],
    ['    q[first] = null;', 7],
    ['    n--;', 7],
    ['    first++;', 8],
    ['    if (first == q.length) first = 0;', 9],
    ['    if (n > 0 && n == q.length / 4) resize(q.length / 2);', 10],
    ['    return item;', 11],
    '}',
    ['private void resize(int capacity) {', 12],
    ['    Item[] copy = (Item[]) new Object[capacity];', 13],
    ['    for (int i = 0; i < n; i++)', 14],
    ['        copy[i] = q[(first + i) % q.length];', 14],
    ['    q = copy;', 15],
    ['    first = 0;', 15],
    ['    last = n;', 15],
    '}',
  ]),
  cpp: code([
    ['void enqueue(int item) {', 1],
    ['    if (n == capacity) resize(2 * capacity);', 2],
    ['    q[last++] = item;', 3],
    ['    if (last == capacity) last = 0;', 4],
    ['    n++;', 5],
    '}',
    ['int dequeue() {', 6],
    ['    int item = q[first];', 7],
    ['    n--;', 7],
    ['    first++;', 8],
    ['    if (first == capacity) first = 0;', 9],
    ['    if (n > 0 && n == capacity / 4) resize(capacity / 2);', 10],
    ['    return item;', 11],
    '}',
    ['void resize(int newCapacity) {', 12],
    ['    int* copy = new int[newCapacity];', 13],
    ['    for (int i = 0; i < n; i++)', 14],
    ['        copy[i] = q[(first + i) % capacity];', 14],
    ['    delete[] q;', 15],
    ['    q = copy; capacity = newCapacity;', 15],
    ['    first = 0; last = n;', 15],
    '}',
  ]),
  python: code([
    ['def enqueue(self, item):', 1],
    ['    if self.n == len(self.q):', 2],
    ['        self.resize(2 * len(self.q))', 2],
    ['    self.q[self.last] = item', 3],
    ['    self.last += 1', 3],
    ['    if self.last == len(self.q):', 4],
    ['        self.last = 0', 4],
    ['    self.n += 1', 5],
    '',
    ['def dequeue(self):', 6],
    ['    item = self.q[self.first]', 7],
    ['    self.q[self.first] = None', 7],
    ['    self.n -= 1', 7],
    ['    self.first += 1', 8],
    ['    if self.first == len(self.q):', 9],
    ['        self.first = 0', 9],
    ['    if self.n > 0 and self.n == len(self.q) // 4:', 10],
    ['        self.resize(len(self.q) // 2)', 10],
    ['    return item', 11],
    '',
    ['def resize(self, capacity):', 12],
    ['    copy = [None] * capacity', 13],
    ['    for i in range(self.n):', 14],
    ['        copy[i] = self.q[(self.first + i) % len(self.q)]', 14],
    ['    self.q = copy', 15],
    ['    self.first = 0', 15],
    ['    self.last = self.n', 15],
  ]),
}

const linked: OperationSnippets = {
  java: code([
    ['public void enqueue(Item item) {', 1],
    ['    Node oldlast = last;', 2],
    ['    last = new Node();', 3],
    ['    last.item = item;', 3],
    ['    last.next = null;', 3],
    ['    if (isEmpty()) first = last;', 4],
    ['    else           oldlast.next = last;', 5],
    ['    n++;', 6],
    '}',
    ['public Item dequeue() {', 7],
    ['    Item item = first.item;', 8],
    ['    first = first.next;', 9],
    ['    n--;', 10],
    ['    if (isEmpty()) last = null;', 11],
    ['    return item;', 12],
    '}',
  ]),
  cpp: code([
    ['void enqueue(int item) {', 1],
    ['    Node* oldlast = last;', 2],
    ['    last = new Node{item, nullptr};', 3],
    ['    if (first == nullptr) first = last;', 4],
    ['    else oldlast->next = last;', 5],
    ['    n++;', 6],
    '}',
    ['int dequeue() {', 7],
    ['    int item = first->item;', 8],
    ['    Node* old = first;', 8],
    ['    first = first->next;', 9],
    ['    delete old;', 9],
    ['    n--;', 10],
    ['    if (first == nullptr) last = nullptr;', 11],
    ['    return item;', 12],
    '}',
  ]),
  python: code([
    ['def enqueue(self, item):', 1],
    ['    oldlast = self.last', 2],
    ['    self.last = Node(item, None)', 3],
    ['    if self.first is None:', 4],
    ['        self.first = self.last', 4],
    ['    else:', 5],
    ['        oldlast.next = self.last', 5],
    ['    self.n += 1', 6],
    '',
    ['def dequeue(self):', 7],
    ['    item = self.first.item', 8],
    ['    self.first = self.first.next', 9],
    ['    self.n -= 1', 10],
    ['    if self.first is None:', 11],
    ['        self.last = None', 11],
    ['    return item', 12],
  ]),
}

export const queueSnippets: Record<string, OperationSnippets> = {
  'array-enqueue': array,
  'array-dequeue': array,
  'linked-enqueue': linked,
  'linked-dequeue': linked,
}
