// SPEC.md §10.11: C++ / Java / Python for each operation, mapped to the pseudocode lines in ./pseudocode.ts.
// Java follows algs4 SequentialSearchST and BinarySearchST; C++ and Python are direct translations.
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const sequential: OperationSnippets = {
  java: code([
    ['public Value get(Key key) {', 1],
    ['    for (Node x = first; x != null; x = x.next)', 2],
    ['        if (key.equals(x.key)) return x.val;', 3],
    ['    return null;', 4],
    '}',
    ['public void put(Key key, Value val) {', 5],
    ['    for (Node x = first; x != null; x = x.next) {', 6],
    ['        if (key.equals(x.key)) { x.val = val; return; }', 7],
    '    }',
    ['    first = new Node(key, val, first);', 8],
    '}',
  ]),
  cpp: code([
    ['int* get(int key) {', 1],
    ['    for (Node* x = first; x != nullptr; x = x->next)', 2],
    ['        if (key == x->key) return &x->val;', 3],
    ['    return nullptr;', 4],
    '}',
    ['void put(int key, int val) {', 5],
    ['    for (Node* x = first; x != nullptr; x = x->next) {', 6],
    ['        if (key == x->key) { x->val = val; return; }', 7],
    '    }',
    ['    first = new Node{key, val, first};', 8],
    '}',
  ]),
  python: code([
    ['def get(self, key):', 1],
    ['    x = self.first', 2],
    ['    while x is not None:', 2],
    ['        if key == x.key:', 3],
    ['            return x.val', 3],
    ['        x = x.next', 2],
    ['    return None', 4],
    '',
    ['def put(self, key, val):', 5],
    ['    x = self.first', 6],
    ['    while x is not None:', 6],
    ['        if key == x.key:', 7],
    ['            x.val = val', 7],
    ['            return', 7],
    ['        x = x.next', 6],
    ['    self.first = Node(key, val, self.first)', 8],
  ]),
}

const binary: OperationSnippets = {
  java: code([
    ['public Value get(Key key) {', 1],
    ['    int i = rank(key);', 2],
    ['    if (i < n && keys[i].compareTo(key) == 0) return vals[i];', 3],
    ['    return null;', 4],
    '}',
    ['public void put(Key key, Value val) {', 5],
    ['    int i = rank(key);', 6],
    ['    if (i < n && keys[i].compareTo(key) == 0) { vals[i] = val; return; }', 7],
    ['    for (int j = n; j > i; j--) {', 8],
    ['        keys[j] = keys[j-1];', 8],
    ['        vals[j] = vals[j-1];', 8],
    '    }',
    ['    keys[i] = key;', 9],
    ['    vals[i] = val;', 9],
    ['    n++;', 9],
    '}',
    ['public int rank(Key key) {', 10],
    ['    int lo = 0, hi = n - 1;', 11],
    ['    while (lo <= hi) {', 12],
    ['        int mid = lo + (hi - lo) / 2;', 13],
    ['        int cmp = key.compareTo(keys[mid]);', 13],
    ['        if      (cmp < 0) hi = mid - 1;', 14],
    ['        else if (cmp > 0) lo = mid + 1;', 15],
    ['        else return mid;', 16],
    '    }',
    ['    return lo;', 17],
    '}',
  ]),
  cpp: code([
    ['int* get(int key) {', 1],
    ['    int i = rank(key);', 2],
    ['    if (i < n && keys[i] == key) return &vals[i];', 3],
    ['    return nullptr;', 4],
    '}',
    ['void put(int key, int val) {', 5],
    ['    int i = rank(key);', 6],
    ['    if (i < n && keys[i] == key) { vals[i] = val; return; }', 7],
    ['    for (int j = n; j > i; j--) {', 8],
    ['        keys[j] = keys[j-1];', 8],
    ['        vals[j] = vals[j-1];', 8],
    '    }',
    ['    keys[i] = key;', 9],
    ['    vals[i] = val;', 9],
    ['    n++;', 9],
    '}',
    ['int rank(int key) {', 10],
    ['    int lo = 0, hi = n - 1;', 11],
    ['    while (lo <= hi) {', 12],
    ['        int mid = lo + (hi - lo) / 2;', 13],
    ['        if      (key < keys[mid]) hi = mid - 1;', 14],
    ['        else if (key > keys[mid]) lo = mid + 1;', 15],
    ['        else return mid;', 16],
    '    }',
    ['    return lo;', 17],
    '}',
  ]),
  python: code([
    ['def get(self, key):', 1],
    ['    i = self.rank(key)', 2],
    ['    if i < self.n and self.keys[i] == key:', 3],
    ['        return self.vals[i]', 3],
    ['    return None', 4],
    '',
    ['def put(self, key, val):', 5],
    ['    i = self.rank(key)', 6],
    ['    if i < self.n and self.keys[i] == key:', 7],
    ['        self.vals[i] = val', 7],
    ['        return', 7],
    ['    for j in range(self.n, i, -1):', 8],
    ['        self.keys[j] = self.keys[j-1]', 8],
    ['        self.vals[j] = self.vals[j-1]', 8],
    ['    self.keys[i] = key', 9],
    ['    self.vals[i] = val', 9],
    ['    self.n += 1', 9],
    '',
    ['def rank(self, key):', 10],
    ['    lo, hi = 0, self.n - 1', 11],
    ['    while lo <= hi:', 12],
    ['        mid = lo + (hi - lo) // 2', 13],
    ['        if key < self.keys[mid]:', 14],
    ['            hi = mid - 1', 14],
    ['        elif key > self.keys[mid]:', 15],
    ['            lo = mid + 1', 15],
    ['        else:', 16],
    ['            return mid', 16],
    ['    return lo', 17],
  ]),
}

export const searchingSnippets: Record<string, OperationSnippets> = {
  'seq-get': sequential,
  'seq-put': sequential,
  'bin-get': binary,
  'bin-put': binary,
}
