// SPEC.md §10.5: C++ / Java / Python for the doubling test, mapped to the pseudocode lines in ./pseudocode.ts.
// The counting loops mirror algs4 OneSum, TwoSum, and ThreeSum; `accesses` counts the array reads each makes.
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const listing: OperationSnippets = {
  java: code([
    ['public static void doublingRatio(String problem, int start) {', 1],
    ['    long prev = 0;', 2],
    ['    int N = start;', 3],
    ['    for (int round = 0; round < 6; round++, N *= 2) {', 3],
    ['        long accesses = accesses(problem, N);', 4],
    ['        double ratio = prev == 0 ? 0 : (double) accesses / prev;', 5],
    ['        StdOut.printf("%7d %12d %5.1f%n", N, accesses, ratio);', 5],
    ['        prev = accesses;', 6],
    '    }',
    '}',
    ['public static long accesses(String problem, int N) {', 7],
    ['    int[] a = new int[N];', 7],
    ['    long accesses = 0;', 7],
    ['    if (problem.equals("1-sum")) {', 8],
    ['        for (int i = 0; i < N; i++)', 8],
    ['            accesses += 1;                       // reads a[i]', 8],
    ['    } else if (problem.equals("2-sum")) {', 9],
    ['        for (int i = 0; i < N; i++)', 9],
    ['            for (int j = i + 1; j < N; j++)', 9],
    ['                accesses += 2;                   // reads a[i], a[j]', 9],
    ['    } else {', 10],
    ['        for (int i = 0; i < N; i++)', 10],
    ['            for (int j = i + 1; j < N; j++)', 10],
    ['                for (int k = j + 1; k < N; k++)', 10],
    ['                    accesses += 3;               // reads a[i], a[j], a[k]', 10],
    '    }',
    ['    return accesses;', 7],
    '}',
  ]),
  cpp: code([
    ['void doublingRatio(const std::string& problem, int start) {', 1],
    ['    long long prev = 0;', 2],
    ['    int N = start;', 3],
    ['    for (int round = 0; round < 6; round++, N *= 2) {', 3],
    ['        long long acc = accesses(problem, N);', 4],
    ['        double ratio = prev == 0 ? 0 : (double) acc / prev;', 5],
    ['        std::printf("%7d %12lld %5.1f\\n", N, acc, ratio);', 5],
    ['        prev = acc;', 6],
    '    }',
    '}',
    ['long long accesses(const std::string& problem, int N) {', 7],
    ['    long long acc = 0;', 7],
    ['    if (problem == "1-sum") {', 8],
    ['        for (int i = 0; i < N; i++)', 8],
    ['            acc += 1;                       // reads a[i]', 8],
    ['    } else if (problem == "2-sum") {', 9],
    ['        for (int i = 0; i < N; i++)', 9],
    ['            for (int j = i + 1; j < N; j++)', 9],
    ['                acc += 2;                   // reads a[i], a[j]', 9],
    ['    } else {', 10],
    ['        for (int i = 0; i < N; i++)', 10],
    ['            for (int j = i + 1; j < N; j++)', 10],
    ['                for (int k = j + 1; k < N; k++)', 10],
    ['                    acc += 3;               // reads a[i], a[j], a[k]', 10],
    '    }',
    ['    return acc;', 7],
    '}',
  ]),
  python: code([
    ['def doubling_ratio(problem, start):', 1],
    ['    prev = 0', 2],
    ['    n = start', 3],
    ['    for _ in range(6):', 3],
    ['        acc = accesses(problem, n)', 4],
    ['        ratio = acc / prev if prev else 0', 5],
    ['        print(f"{n:7d} {acc:12d} {ratio:5.1f}")', 5],
    ['        prev = acc', 6],
    ['        n *= 2', 3],
    '',
    ['def accesses(problem, n):', 7],
    ['    acc = 0', 7],
    ['    if problem == "1-sum":', 8],
    ['        for i in range(n):', 8],
    ['            acc += 1  # reads a[i]', 8],
    ['    elif problem == "2-sum":', 9],
    ['        for i in range(n):', 9],
    ['            for j in range(i + 1, n):', 9],
    ['                acc += 2  # reads a[i], a[j]', 9],
    ['    else:', 10],
    ['        for i in range(n):', 10],
    ['            for j in range(i + 1, n):', 10],
    ['                for k in range(j + 1, n):', 10],
    ['                    acc += 3  # reads a[i], a[j], a[k]', 10],
    ['    return acc', 7],
  ]),
}

export const complexitySnippets: Record<string, OperationSnippets> = {
  'doubling-ratio': listing,
  'count-accesses': listing,
}
