// SPEC.md §10: C++ / Java / Python for each operation, mapped to the pseudocode lines in ./pseudocode.ts.
// Java follows algs4's MaxPQ (pq[] is 1-indexed, n is the size, less/exch helpers).
// For a min-heap, less(i, j) compares the other way round; nothing else changes.
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const insert: OperationSnippets = {
  java: code([
    ['public void insert(int value) {', 1],
    ['    pq[++n] = value;', 3],
    ['    swim(n);', 4],
    '}',
    ['private void swim(int k) {', 5],
    ['    while (k > 1 && less(k/2, k)) {', 6],
    ['        exch(k/2, k);', 7],
    ['        k = k/2;', 8],
    '    }',
    '}',
  ]),
  cpp: code([
    ['void insert(int value) {', 1],
    ['    pq[++n] = value;', 3],
    ['    swim(n);', 4],
    '}',
    ['void swim(int k) {', 5],
    ['    while (k > 1 && less(k / 2, k)) {', 6],
    ['        std::swap(pq[k / 2], pq[k]);', 7],
    ['        k = k / 2;', 8],
    '    }',
    '}',
  ]),
  python: code([
    ['def insert(self, value):', 1],
    ['    self.n += 1', 2],
    ['    self.pq[self.n] = value', 3],
    ['    self.swim(self.n)', 4],
    '',
    ['def swim(self, k):', 5],
    ['    while k > 1 and self.less(k // 2, k):', 6],
    ['        self.exch(k // 2, k)', 7],
    ['        k = k // 2', 8],
  ]),
}

const remove: OperationSnippets = {
  java: code([
    ['public int delMax() {', 1],
    ['    int max = pq[1];', 2],
    ['    exch(1, n--);', 3],
    ['    sink(1);', 5],
    ['    return max;', 6],
    '}',
    ['private void sink(int k) {', 7],
    ['    while (2*k <= n) {', 8],
    ['        int j = 2*k;', 9],
    ['        if (j < n && less(j, j+1)) j++;', 10],
    ['        if (!less(k, j)) break;', 11],
    ['        exch(k, j);', 12],
    ['        k = j;', 13],
    '    }',
    '}',
  ]),
  cpp: code([
    ['int delMax() {', 1],
    ['    int max = pq[1];', 2],
    ['    std::swap(pq[1], pq[n--]);', 3],
    ['    sink(1);', 5],
    ['    return max;', 6],
    '}',
    ['void sink(int k) {', 7],
    ['    while (2 * k <= n) {', 8],
    ['        int j = 2 * k;', 9],
    ['        if (j < n && less(j, j + 1)) j++;', 10],
    ['        if (!less(k, j)) break;', 11],
    ['        std::swap(pq[k], pq[j]);', 12],
    ['        k = j;', 13],
    '    }',
    '}',
  ]),
  python: code([
    ['def del_max(self):', 1],
    ['    maximum = self.pq[1]', 2],
    ['    self.exch(1, self.n)', 3],
    ['    self.n -= 1', 4],
    ['    self.sink(1)', 5],
    ['    return maximum', 6],
    '',
    ['def sink(self, k):', 7],
    ['    while 2 * k <= self.n:', 8],
    ['        j = 2 * k', 9],
    ['        if j < self.n and self.less(j, j + 1):', 10],
    ['            j += 1', 10],
    ['        if not self.less(k, j):', 11],
    ['            break', 11],
    ['        self.exch(k, j)', 12],
    ['        k = j', 13],
  ]),
}

const buildHeap: OperationSnippets = {
  java: code([
    ['public void buildHeap(int[] a) {', 1],
    ['    pq = a; n = a.length - 1;', 2],
    ['    for (int k = n/2; k >= 1; k--)', 3],
    ['        sink(k);', 4],
    '}',
    ['private void sink(int k) {', 5],
    ['    while (2*k <= n) {', 6],
    ['        int j = 2*k;', 7],
    ['        if (j < n && less(j, j+1)) j++;', 8],
    ['        if (!less(k, j)) break;', 9],
    ['        exch(k, j);', 10],
    ['        k = j;', 11],
    '    }',
    '}',
  ]),
  cpp: code([
    ['void buildHeap(const std::vector<int>& a) {', 1],
    ['    pq = a; n = a.size() - 1;', 2],
    ['    for (int k = n / 2; k >= 1; k--)', 3],
    ['        sink(k);', 4],
    '}',
    ['void sink(int k) {', 5],
    ['    while (2 * k <= n) {', 6],
    ['        int j = 2 * k;', 7],
    ['        if (j < n && less(j, j + 1)) j++;', 8],
    ['        if (!less(k, j)) break;', 9],
    ['        std::swap(pq[k], pq[j]);', 10],
    ['        k = j;', 11],
    '    }',
    '}',
  ]),
  python: code([
    ['def build_heap(self, a):', 1],
    ['    self.pq = [None] + list(a)', 2],
    ['    self.n = len(a)', 2],
    ['    for k in range(self.n // 2, 0, -1):', 3],
    ['        self.sink(k)', 4],
    '',
    ['def sink(self, k):', 5],
    ['    while 2 * k <= self.n:', 6],
    ['        j = 2 * k', 7],
    ['        if j < self.n and self.less(j, j + 1):', 8],
    ['            j += 1', 8],
    ['        if not self.less(k, j):', 9],
    ['            break', 9],
    ['        self.exch(k, j)', 10],
    ['        k = j', 11],
  ]),
}

const heapsort: OperationSnippets = {
  java: code([
    ['public static void sort(int[] a) {', 1],
    ['    int n = a.length - 1;', 2],
    ['    for (int k = n/2; k >= 1; k--) sink(a, k, n);', 2],
    ['    while (n > 1) {', 3],
    ['        exch(a, 1, n);', 4],
    ['        n--;', 5],
    ['        sink(a, 1, n);', 6],
    '    }',
    '}',
    ['private static void sink(int[] a, int k, int n) {', 7],
    ['    while (2*k <= n) {', 8],
    ['        int j = 2*k;', 9],
    ['        if (j < n && less(a, j, j+1)) j++;', 10],
    ['        if (!less(a, k, j)) break;', 11],
    ['        exch(a, k, j);', 12],
    ['        k = j;', 13],
    '    }',
    '}',
  ]),
  cpp: code([
    ['void heapsort(std::vector<int>& a) {', 1],
    ['    int n = a.size() - 1;', 2],
    ['    for (int k = n / 2; k >= 1; k--) sink(a, k, n);', 2],
    ['    while (n > 1) {', 3],
    ['        std::swap(a[1], a[n]);', 4],
    ['        n--;', 5],
    ['        sink(a, 1, n);', 6],
    '    }',
    '}',
    ['void sink(std::vector<int>& a, int k, int n) {', 7],
    ['    while (2 * k <= n) {', 8],
    ['        int j = 2 * k;', 9],
    ['        if (j < n && less(a, j, j + 1)) j++;', 10],
    ['        if (!less(a, k, j)) break;', 11],
    ['        std::swap(a[k], a[j]);', 12],
    ['        k = j;', 13],
    '    }',
    '}',
  ]),
  python: code([
    ['def heapsort(a):', 1],
    ['    n = len(a) - 1', 2],
    ['    for k in range(n // 2, 0, -1):', 2],
    ['        sink(a, k, n)', 2],
    ['    while n > 1:', 3],
    ['        a[1], a[n] = a[n], a[1]', 4],
    ['        n -= 1', 5],
    ['        sink(a, 1, n)', 6],
    '',
    ['def sink(a, k, n):', 7],
    ['    while 2 * k <= n:', 8],
    ['        j = 2 * k', 9],
    ['        if j < n and less(a, j, j + 1):', 10],
    ['            j += 1', 10],
    ['        if not less(a, k, j):', 11],
    ['            break', 11],
    ['        a[k], a[j] = a[j], a[k]', 12],
    ['        k = j', 13],
  ]),
}

export const heapSnippets: Record<string, OperationSnippets> = {
  insert,
  'remove-max': remove,
  'remove-min': remove,
  'build-heap': buildHeap,
  heapsort,
}
