// SPEC.md §19.0 quiz. Explanations cite the week reference; predict questions run on the seed.
import type { QuizQuestion } from '@/types/case-study'

export const canteenQuiz: QuizQuestion[] = [
  {
    kind: 'choice',
    id: 'canteen-queue',
    prompt: 'Why does the counter keep waiting orders in a queue rather than a stack?',
    choices: [
      'A stack cannot grow past a fixed size.',
      'A stack serves the newest order first, so students who ordered earlier wait longer.',
      'A queue uses less memory than a stack.',
      'A stack cannot be built from linked nodes.',
    ],
    answer: 1,
    explanation: 'Week 3: a queue removes items in the order they were added. When whoever asked first must be served first, reordering is a correctness bug. The skipped counter in the stack design shows it happening.',
    topicSlug: 'queue',
  },
  {
    kind: 'choice',
    id: 'canteen-sorted-log',
    prompt: 'Why can the queue design use binary search on its served log?',
    choices: [
      'Binary search works on any array.',
      'The log is a linked list.',
      'Order numbers are unique, and that is all binary search needs.',
      'The queue serves orders in number order, so the log is already sorted.',
    ],
    answer: 3,
    explanation: 'Week 7: binary search depends on the keys being in order. Order numbers only grow and the queue serves them in that order, so every append keeps the log sorted.',
    topicSlug: 'searching',
  },
  {
    kind: 'choice',
    id: 'canteen-lg-n',
    prompt: 'The served log holds 1,000 orders. At most how many compares does binary search need?',
    choices: ['1,000', 'About 500', 'About 11', 'About 100'],
    answer: 2,
    explanation: 'Week 7: binary search needs no more than lg N + 1 compares. lg 1,000 is just under 10, so the bound is about 11. Sequential search can need all 1,000.',
    topicSlug: 'searching',
  },
  {
    kind: 'choice',
    id: 'canteen-doubling',
    prompt: 'The log grows from 1,000 to 2,000 orders. How does the worst case of each search change?',
    choices: [
      'Sequential search doubles, and binary search needs about one more compare.',
      'Both double.',
      'Neither changes.',
      'Binary search doubles, and sequential search needs about one more compare.',
    ],
    answer: 0,
    explanation: 'Up to N compares doubles when N doubles, and lg N + 1 grows by one (Week 7). Week 1 asks exactly this question: does a program keep working as the input grows?',
    topicSlug: 'complexity',
  },
  {
    kind: 'choice',
    id: 'canteen-linked',
    prompt: 'Why are the waiting orders kept on linked nodes?',
    choices: [
      'Linked nodes keep the orders sorted.',
      'The counter cannot know how many orders will wait, and linked nodes add and remove at the ends in constant time.',
      'Linked nodes allow binary search.',
      'Linked nodes use less memory per order than an array slot.',
    ],
    answer: 1,
    explanation: 'Week 6: a linked list grows and shrinks one item at a time without knowing its final size, with constant-time insertion and removal at the ends.',
    topicSlug: 'linked-list',
  },
  {
    kind: 'choice',
    id: 'canteen-resize',
    prompt: 'The served log is full at 4 slots when the kitchen serves another order. What does the counter do?',
    choices: [
      'It refuses to serve the order.',
      'It overwrites the oldest entry.',
      'It adds one slot and copies the log.',
      'It doubles the log to 8 slots, copies the 4 orders, then writes the new one.',
    ],
    answer: 3,
    explanation: 'Week 3: a resizing array doubles when full, which keeps the amortized cost per operation constant. Growing by one slot would copy the whole log on every serve.',
    topicSlug: 'arrays',
  },
  {
    kind: 'predict',
    id: 'canteen-predict-binary',
    prompt: 'Binary search for order 101 probes the middle of the log and finds order 102. What happens next?',
    operationId: 'find-binary',
    variant: 'queue',
    input: 101,
    stepIndex: 0,
    expect: 'so search the left half',
    choices: [
      '101 > 102, so search the right half.',
      '101 < 102, so search the left half.',
      'Compare 101 with every order after 102.',
      'Order 101 is not in the served log.',
    ],
    answer: 1,
    explanation: 'The log is sorted and 101 is smaller than 102, so 101 can only be to its left: hi becomes mid - 1 (Week 7).',
    topicSlug: 'searching',
  },
  {
    kind: 'predict',
    id: 'canteen-predict-push',
    prompt: 'In the stack design the counter has just numbered order 107. Where does it go?',
    operationId: 'place-stack',
    variant: 'stack',
    input: undefined,
    stepIndex: 0,
    expect: 'goes on top of the stack, above order 106',
    choices: [
      'Order 107 joins the back, behind order 101.',
      'Order 107 goes straight into the served log.',
      'Order 107 goes on top of the stack, above order 106.',
      'Order 107 replaces order 106.',
    ],
    answer: 2,
    explanation: 'A push adds at the top, which is where the next pop takes from, so 107 will be served before 106, 105, and 101, all placed earlier (Week 4).',
    topicSlug: 'stack',
  },
]
