// SPEC.md §10.12: pseudocode, verbatim.
export const bTreePseudocode: Record<string, string[]> = {
  get: [
    'GET(key): return SEARCH(root, key, height)',
    'SEARCH(x, key, ht):',
    '  if ht == 0:',
    '    for j = 0 to x.m - 1: if key == x.entry[j].key: return x.entry[j].val',
    '  else:',
    '    for j = 0 to x.m - 1:',
    '      if j + 1 == x.m or key < x.entry[j+1].key: return SEARCH(x.entry[j].child, key, ht - 1)',
    '  return null',
  ],
  put: [
    'PUT(key, val):',
    '  u = INSERT(root, key, val, height)',
    '  if u is null: return',
    '  root = NODE(ENTRY(root.entry[0].key, root), ENTRY(u.entry[0].key, u)); height = height + 1',
    'INSERT(h, key, val, ht):',
    '  t = ENTRY(key, val)',
    '  if ht == 0: j = number of entries in h with key < new key',
    '  else:',
    '    find j with j + 1 == h.m or key < h.entry[j+1].key',
    '    if key < h.entry[j].key: h.entry[j].key = key',
    '    u = INSERT(h.entry[j].child, key, val, ht - 1)',
    '    if u is null: return null',
    '    t = ENTRY(u.entry[0].key, u); j = j + 1',
    '  shift h.entry[j..] right; h.entry[j] = t; h.m = h.m + 1',
    '  if h.m < M: return null',
    '  return SPLIT(h)',
    'SPLIT(h):',
    '  t = NODE(h.entry[M/2 .. M-1]); h.m = M / 2',
    '  return t',
  ],
}
