// SPEC.md §10.12: C++ / Java / Python for each operation, mapped to the pseudocode lines in ./pseudocode.ts.
// Java is algs4 BTree.java (M = 4) plus one line that keeps a guide key equal to its subtree's
// smallest key (SPEC.md §10.12); C++ and Python are direct translations of it.
import { code } from '@/lib/snippets'
import type { OperationSnippets } from '@/types/step-engine'

const get: OperationSnippets = {
  java: code([
    ['public Value get(Key key) { return search(root, key, height); }', 1],
    ['private Value search(Node x, Key key, int ht) {', 2],
    ['    Entry[] children = x.children;', 2],
    ['    if (ht == 0) {', 3],
    ['        for (int j = 0; j < x.m; j++)', 4],
    ['            if (eq(key, children[j].key)) return (Value) children[j].val;', 4],
    '    }',
    ['    else {', 5],
    ['        for (int j = 0; j < x.m; j++)', 6],
    ['            if (j+1 == x.m || less(key, children[j+1].key))', 7],
    ['                return search(children[j].next, key, ht-1);', 7],
    '    }',
    ['    return null;', 8],
    '}',
  ]),
  cpp: code([
    ['Value* get(Key key) { return search(root, key, height); }', 1],
    ['Value* search(Node* x, Key key, int ht) {', 2],
    ['    if (ht == 0) {', 3],
    ['        for (int j = 0; j < x->m; j++)', 4],
    ['            if (key == x->children[j].key) return &x->children[j].val;', 4],
    '    }',
    ['    else {', 5],
    ['        for (int j = 0; j < x->m; j++)', 6],
    ['            if (j+1 == x->m || key < x->children[j+1].key)', 7],
    ['                return search(x->children[j].next, key, ht-1);', 7],
    '    }',
    ['    return nullptr;', 8],
    '}',
  ]),
  python: code([
    ['def get(self, key):', 1],
    ['    return self._search(self.root, key, self.height)', 1],
    '',
    ['def _search(self, x, key, ht):', 2],
    ['    if ht == 0:', 3],
    ['        for j in range(x.m):', 4],
    ['            if key == x.children[j].key:', 4],
    ['                return x.children[j].val', 4],
    ['    else:', 5],
    ['        for j in range(x.m):', 6],
    ['            if j + 1 == x.m or key < x.children[j + 1].key:', 7],
    ['                return self._search(x.children[j].next, key, ht - 1)', 7],
    ['    return None', 8],
  ]),
}

const put: OperationSnippets = {
  java: code([
    ['public void put(Key key, Value val) {', 1],
    ['    Node u = insert(root, key, val, height);', 2],
    ['    n++;', 2],
    ['    if (u == null) return;', 3],
    ['    Node t = new Node(2);', 4],
    ['    t.children[0] = new Entry(root.children[0].key, null, root);', 4],
    ['    t.children[1] = new Entry(u.children[0].key, null, u);', 4],
    ['    root = t;', 4],
    ['    height++;', 4],
    '}',
    ['private Node insert(Node h, Key key, Value val, int ht) {', 5],
    ['    int j;', 5],
    ['    Entry t = new Entry(key, val, null);', 6],
    ['    if (ht == 0) {', 7],
    ['        for (j = 0; j < h.m; j++)', 7],
    ['            if (less(key, h.children[j].key)) break;', 7],
    '    }',
    ['    else {', 8],
    ['        for (j = 0; j < h.m; j++) {', 9],
    ['            if ((j+1 == h.m) || less(key, h.children[j+1].key)) {', 9],
    ['                if (less(key, h.children[j].key)) h.children[j].key = key;', 10],
    ['                Node u = insert(h.children[j++].next, key, val, ht-1);', 11],
    ['                if (u == null) return null;', 12],
    ['                t.key = u.children[0].key;', 13],
    ['                t.next = u;', 13],
    '                break;',
    '            }',
    '        }',
    '    }',
    ['    for (int i = h.m; i > j; i--) h.children[i] = h.children[i-1];', 14],
    ['    h.children[j] = t;', 14],
    ['    h.m++;', 14],
    ['    if (h.m < M) return null;', 15],
    ['    else         return split(h);', 16],
    '}',
    ['private Node split(Node h) {', 17],
    ['    Node t = new Node(M/2);', 18],
    ['    h.m = M/2;', 18],
    ['    for (int j = 0; j < M/2; j++) t.children[j] = h.children[M/2+j];', 18],
    ['    return t;', 19],
    '}',
  ]),
  cpp: code([
    ['void put(Key key, Value val) {', 1],
    ['    Node* u = insert(root, key, val, height);', 2],
    ['    n++;', 2],
    ['    if (u == nullptr) return;', 3],
    ['    Node* t = new Node(2);', 4],
    ['    t->children[0] = Entry(root->children[0].key, root);', 4],
    ['    t->children[1] = Entry(u->children[0].key, u);', 4],
    ['    root = t;', 4],
    ['    height++;', 4],
    '}',
    ['Node* insert(Node* h, Key key, Value val, int ht) {', 5],
    ['    int j;', 5],
    ['    Entry t(key, val);', 6],
    ['    if (ht == 0) {', 7],
    ['        for (j = 0; j < h->m; j++)', 7],
    ['            if (key < h->children[j].key) break;', 7],
    '    }',
    ['    else {', 8],
    ['        for (j = 0; j < h->m; j++) {', 9],
    ['            if (j+1 == h->m || key < h->children[j+1].key) {', 9],
    ['                if (key < h->children[j].key) h->children[j].key = key;', 10],
    ['                Node* u = insert(h->children[j++].next, key, val, ht-1);', 11],
    ['                if (u == nullptr) return nullptr;', 12],
    ['                t.key = u->children[0].key;', 13],
    ['                t.next = u;', 13],
    '                break;',
    '            }',
    '        }',
    '    }',
    ['    for (int i = h->m; i > j; i--) h->children[i] = h->children[i-1];', 14],
    ['    h->children[j] = t;', 14],
    ['    h->m++;', 14],
    ['    if (h->m < M) return nullptr;', 15],
    ['    return split(h);', 16],
    '}',
    ['Node* split(Node* h) {', 17],
    ['    Node* t = new Node(M/2);', 18],
    ['    h->m = M/2;', 18],
    ['    for (int j = 0; j < M/2; j++) t->children[j] = h->children[M/2+j];', 18],
    ['    return t;', 19],
    '}',
  ]),
  python: code([
    ['def put(self, key, val):', 1],
    ['    u = self._insert(self.root, key, val, self.height)', 2],
    ['    self.n += 1', 2],
    ['    if u is None:', 3],
    ['        return', 3],
    ['    t = Node(2)', 4],
    ['    t.children[0] = Entry(self.root.children[0].key, None, self.root)', 4],
    ['    t.children[1] = Entry(u.children[0].key, None, u)', 4],
    ['    self.root = t', 4],
    ['    self.height += 1', 4],
    '',
    ['def _insert(self, h, key, val, ht):', 5],
    ['    t = Entry(key, val, None)', 6],
    ['    if ht == 0:', 7],
    ['        j = 0', 7],
    ['        while j < h.m and not key < h.children[j].key:', 7],
    ['            j += 1', 7],
    ['    else:', 8],
    ['        for j in range(h.m):', 9],
    ['            if j + 1 == h.m or key < h.children[j + 1].key:', 9],
    ['                if key < h.children[j].key:', 10],
    ['                    h.children[j].key = key', 10],
    ['                u = self._insert(h.children[j].next, key, val, ht - 1)', 11],
    ['                j += 1', 11],
    ['                if u is None:', 12],
    ['                    return None', 12],
    ['                t.key = u.children[0].key', 13],
    ['                t.next = u', 13],
    '                break',
    ['    h.children.insert(j, t)', 14],
    ['    h.m += 1', 14],
    ['    if h.m < M:', 15],
    ['        return None', 15],
    ['    return self._split(h)', 16],
    '',
    ['def _split(self, h):', 17],
    ['    t = Node(M // 2)', 18],
    ['    t.children = h.children[M // 2:]', 18],
    ['    h.children = h.children[:M // 2]', 18],
    ['    h.m = M // 2', 18],
    ['    return t', 19],
  ]),
}

export const bTreeSnippets: Record<string, OperationSnippets> = { get, put }
